namespace LVGLSharp.Interop
{
    public enum lv_imagebutton_state_t
    {
        LV_IMAGEBUTTON_STATE_RELEASED,
        LV_IMAGEBUTTON_STATE_PRESSED,
        LV_IMAGEBUTTON_STATE_DISABLED,
        LV_IMAGEBUTTON_STATE_CHECKED_RELEASED,
        LV_IMAGEBUTTON_STATE_CHECKED_PRESSED,
        LV_IMAGEBUTTON_STATE_CHECKED_DISABLED,
        LV_IMAGEBUTTON_STATE_NUM,
    }
}
