#include <lv_conf.h>
#include <lvgl.h>
#include <new>

lv_mem_monitor_t& (lv_mem_monitor_t::*_0)(lv_mem_monitor_t&&) = &lv_mem_monitor_t::operator=;
struct _lv_timer_t& (_lv_timer_t::*_1)(struct _lv_timer_t&&) = &_lv_timer_t::operator=;
lv_timer_state_t& (lv_timer_state_t::*_2)(lv_timer_state_t&&) = &lv_timer_state_t::operator=;
lv_tick_state_t& (lv_tick_state_t::*_3)(lv_tick_state_t&&) = &lv_tick_state_t::operator=;
lv_ll_t& (lv_ll_t::*_4)(lv_ll_t&&) = &lv_ll_t::operator=;
lv_sqrt_res_t& (lv_sqrt_res_t::*_5)(lv_sqrt_res_t&&) = &lv_sqrt_res_t::operator=;
lv_array_t& (lv_array_t::*_6)(lv_array_t&&) = &lv_array_t::operator=;
lv_anim_state_t& (lv_anim_state_t::*_7)(lv_anim_state_t&&) = &lv_anim_state_t::operator=;
struct _lv_anim_bezier3_para_t& (_lv_anim_bezier3_para_t::*_8)(struct _lv_anim_bezier3_para_t&&) = &_lv_anim_bezier3_para_t::operator=;
union _lv_anim_t::_lv_anim_path_para_t& (_lv_anim_t::_lv_anim_path_para_t::*_9)(union _lv_anim_t::_lv_anim_path_para_t&&) = &_lv_anim_t::_lv_anim_path_para_t::operator=;
struct _lv_anim_t& (_lv_anim_t::*_10)(struct _lv_anim_t&&) = &_lv_anim_t::operator=;
lv_rb_node_t& (lv_rb_node_t::*_11)(lv_rb_node_t&&) = &lv_rb_node_t::operator=;
lv_rb_t& (lv_rb_t::*_12)(lv_rb_t&&) = &lv_rb_t::operator=;
_lv_obj_spec_attr_t& (_lv_obj_spec_attr_t::*_13)(_lv_obj_spec_attr_t&&) = &_lv_obj_spec_attr_t::operator=;
struct _lv_obj_t& (_lv_obj_t::*_14)(struct _lv_obj_t&&) = &_lv_obj_t::operator=;
struct _lv_obj_class_t& (_lv_obj_class_t::*_15)(struct _lv_obj_class_t&&) = &_lv_obj_class_t::operator=;
lv_gradient_stop_t& (lv_gradient_stop_t::*_16)(lv_gradient_stop_t&&) = &lv_gradient_stop_t::operator=;
lv_grad_dsc_t& (lv_grad_dsc_t::*_17)(lv_grad_dsc_t&&) = &lv_grad_dsc_t::operator=;
lv_style_value_t& (lv_style_value_t::*_18)(lv_style_value_t&&) = &lv_style_value_t::operator=;
lv_style_transition_dsc_t& (lv_style_transition_dsc_t::*_19)(lv_style_transition_dsc_t&&) = &lv_style_transition_dsc_t::operator=;
lv_style_const_prop_t& (lv_style_const_prop_t::*_20)(lv_style_const_prop_t&&) = &lv_style_const_prop_t::operator=;
lv_style_t& (lv_style_t::*_21)(lv_style_t&&) = &lv_style_t::operator=;
lv_font_glyph_dsc_t& (lv_font_glyph_dsc_t::*_22)(lv_font_glyph_dsc_t&&) = &lv_font_glyph_dsc_t::operator=;
struct _lv_font_t& (_lv_font_t::*_23)(struct _lv_font_t&&) = &_lv_font_t::operator=;
lv_draw_buf_t& (lv_draw_buf_t::*_24)(lv_draw_buf_t&&) = &lv_draw_buf_t::operator=;
lv_draw_buf_handlers_t& (lv_draw_buf_handlers_t::*_25)(lv_draw_buf_handlers_t&&) = &lv_draw_buf_handlers_t::operator=;
lv_point_t& (lv_point_t::*_26)(lv_point_t&&) = &lv_point_t::operator=;
lv_point_precise_t& (lv_point_precise_t::*_27)(lv_point_precise_t&&) = &lv_point_precise_t::operator=;
lv_area_t& (lv_area_t::*_28)(lv_area_t&&) = &lv_area_t::operator=;
lv_color_t& (lv_color_t::*_29)(lv_color_t&&) = &lv_color_t::operator=;
lv_color16_t& (lv_color16_t::*_30)(lv_color16_t&&) = &lv_color16_t::operator=;
lv_color32_t& (lv_color32_t::*_31)(lv_color32_t&&) = &lv_color32_t::operator=;
lv_color_hsv_t& (lv_color_hsv_t::*_32)(lv_color_hsv_t&&) = &lv_color_hsv_t::operator=;
lv_color16a_t& (lv_color16a_t::*_33)(lv_color16a_t&&) = &lv_color16a_t::operator=;
struct _lv_color_filter_dsc_t& (_lv_color_filter_dsc_t::*_34)(struct _lv_color_filter_dsc_t&&) = &_lv_color_filter_dsc_t::operator=;
lv_image_header_t& (lv_image_header_t::*_35)(lv_image_header_t&&) = &lv_image_header_t::operator=;
lv_yuv_plane_t& (lv_yuv_plane_t::*_36)(lv_yuv_plane_t&&) = &lv_yuv_plane_t::operator=;
lv_yuv_buf_t& (lv_yuv_buf_t::*_37)(lv_yuv_buf_t&&) = &lv_yuv_buf_t::operator=;
lv_image_dsc_t& (lv_image_dsc_t::*_38)(lv_image_dsc_t&&) = &lv_image_dsc_t::operator=;
lv_thread_sync_t& (lv_thread_sync_t::*_39)(lv_thread_sync_t&&) = &lv_thread_sync_t::operator=;
struct _lv_cache_ops_t& (_lv_cache_ops_t::*_40)(struct _lv_cache_ops_t&&) = &_lv_cache_ops_t::operator=;
struct _lv_cache_t& (_lv_cache_t::*_41)(struct _lv_cache_t&&) = &_lv_cache_t::operator=;
struct _lv_cache_class_t& (_lv_cache_class_t::*_42)(struct _lv_cache_class_t&&) = &_lv_cache_class_t::operator=;
struct _lv_cache_slot_size_t& (_lv_cache_slot_size_t::*_43)(struct _lv_cache_slot_size_t&&) = &_lv_cache_slot_size_t::operator=;
lv_layout_dsc_t& (lv_layout_dsc_t::*_44)(lv_layout_dsc_t&&) = &lv_layout_dsc_t::operator=;
lv_event_dsc_t& (lv_event_dsc_t::*_45)(lv_event_dsc_t&&) = &lv_event_dsc_t::operator=;
struct _lv_event_t& (_lv_event_t::*_46)(struct _lv_event_t&&) = &_lv_event_t::operator=;
struct _lv_draw_task_t& (_lv_draw_task_t::*_47)(struct _lv_draw_task_t&&) = &_lv_draw_task_t::operator=;
lv_draw_mask_t& (lv_draw_mask_t::*_48)(lv_draw_mask_t&&) = &lv_draw_mask_t::operator=;
struct _lv_draw_unit_t& (_lv_draw_unit_t::*_49)(struct _lv_draw_unit_t&&) = &_lv_draw_unit_t::operator=;
struct _lv_layer_t& (_lv_layer_t::*_50)(struct _lv_layer_t&&) = &_lv_layer_t::operator=;
lv_draw_dsc_base_t& (lv_draw_dsc_base_t::*_51)(lv_draw_dsc_base_t&&) = &lv_draw_dsc_base_t::operator=;
lv_draw_global_info_t& (lv_draw_global_info_t::*_52)(lv_draw_global_info_t&&) = &lv_draw_global_info_t::operator=;
struct _lv_image_decoder_args_t& (_lv_image_decoder_args_t::*_53)(struct _lv_image_decoder_args_t&&) = &_lv_image_decoder_args_t::operator=;
struct _lv_image_decoder_t& (_lv_image_decoder_t::*_54)(struct _lv_image_decoder_t&&) = &_lv_image_decoder_t::operator=;
struct _lv_image_decoder_cache_data_t& (_lv_image_decoder_cache_data_t::*_55)(struct _lv_image_decoder_cache_data_t&&) = &_lv_image_decoder_cache_data_t::operator=;
struct _lv_image_decoder_header_cache_data_t& (_lv_image_decoder_header_cache_data_t::*_56)(struct _lv_image_decoder_header_cache_data_t&&) = &_lv_image_decoder_header_cache_data_t::operator=;
struct _lv_image_decoder_dsc_t& (_lv_image_decoder_dsc_t::*_57)(struct _lv_image_decoder_dsc_t&&) = &_lv_image_decoder_dsc_t::operator=;
struct _lv_fs_drv_t& (_lv_fs_drv_t::*_58)(struct _lv_fs_drv_t&&) = &_lv_fs_drv_t::operator=;
lv_fs_file_cache_t& (lv_fs_file_cache_t::*_59)(lv_fs_file_cache_t&&) = &lv_fs_file_cache_t::operator=;
lv_fs_file_t& (lv_fs_file_t::*_60)(lv_fs_file_t&&) = &lv_fs_file_t::operator=;
lv_fs_path_ex_t& (lv_fs_path_ex_t::*_61)(lv_fs_path_ex_t&&) = &lv_fs_path_ex_t::operator=;
lv_fs_dir_t& (lv_fs_dir_t::*_62)(lv_fs_dir_t&&) = &lv_fs_dir_t::operator=;
lv_draw_rect_dsc_t& (lv_draw_rect_dsc_t::*_63)(lv_draw_rect_dsc_t&&) = &lv_draw_rect_dsc_t::operator=;
lv_draw_fill_dsc_t& (lv_draw_fill_dsc_t::*_64)(lv_draw_fill_dsc_t&&) = &lv_draw_fill_dsc_t::operator=;
lv_draw_border_dsc_t& (lv_draw_border_dsc_t::*_65)(lv_draw_border_dsc_t&&) = &lv_draw_border_dsc_t::operator=;
lv_draw_box_shadow_dsc_t& (lv_draw_box_shadow_dsc_t::*_66)(lv_draw_box_shadow_dsc_t&&) = &lv_draw_box_shadow_dsc_t::operator=;
struct _lv_gradient_cache_t& (_lv_gradient_cache_t::*_67)(struct _lv_gradient_cache_t&&) = &_lv_gradient_cache_t::operator=;
struct _lv_draw_label_hint_t& (_lv_draw_label_hint_t::*_68)(struct _lv_draw_label_hint_t&&) = &_lv_draw_label_hint_t::operator=;
lv_draw_label_dsc_t& (lv_draw_label_dsc_t::*_69)(lv_draw_label_dsc_t&&) = &lv_draw_label_dsc_t::operator=;
lv_draw_glyph_dsc_t& (lv_draw_glyph_dsc_t::*_70)(lv_draw_glyph_dsc_t&&) = &lv_draw_glyph_dsc_t::operator=;
lv_draw_image_sup_t& (lv_draw_image_sup_t::*_71)(lv_draw_image_sup_t&&) = &lv_draw_image_sup_t::operator=;
struct _lv_draw_image_dsc_t& (_lv_draw_image_dsc_t::*_72)(struct _lv_draw_image_dsc_t&&) = &_lv_draw_image_dsc_t::operator=;
lv_draw_arc_dsc_t& (lv_draw_arc_dsc_t::*_73)(lv_draw_arc_dsc_t&&) = &lv_draw_arc_dsc_t::operator=;
lv_draw_line_dsc_t& (lv_draw_line_dsc_t::*_74)(lv_draw_line_dsc_t&&) = &lv_draw_line_dsc_t::operator=;
lv_draw_triangle_dsc_t& (lv_draw_triangle_dsc_t::*_75)(lv_draw_triangle_dsc_t&&) = &lv_draw_triangle_dsc_t::operator=;
lv_draw_mask_rect_dsc_t& (lv_draw_mask_rect_dsc_t::*_76)(lv_draw_mask_rect_dsc_t&&) = &lv_draw_mask_rect_dsc_t::operator=;
_lv_obj_style_t& (_lv_obj_style_t::*_77)(_lv_obj_style_t&&) = &_lv_obj_style_t::operator=;
_lv_obj_style_transition_dsc_t& (_lv_obj_style_transition_dsc_t::*_78)(_lv_obj_style_transition_dsc_t&&) = &_lv_obj_style_transition_dsc_t::operator=;
lv_hit_test_info_t& (lv_hit_test_info_t::*_79)(lv_hit_test_info_t&&) = &lv_hit_test_info_t::operator=;
lv_cover_check_info_t& (lv_cover_check_info_t::*_80)(lv_cover_check_info_t&&) = &lv_cover_check_info_t::operator=;
lv_indev_data_t& (lv_indev_data_t::*_81)(lv_indev_data_t&&) = &lv_indev_data_t::operator=;
struct _lv_group_t& (_lv_group_t::*_82)(struct _lv_group_t&&) = &_lv_group_t::operator=;
lv_font_fmt_txt_glyph_dsc_t& (lv_font_fmt_txt_glyph_dsc_t::*_83)(lv_font_fmt_txt_glyph_dsc_t&&) = &lv_font_fmt_txt_glyph_dsc_t::operator=;
lv_font_fmt_txt_cmap_t& (lv_font_fmt_txt_cmap_t::*_84)(lv_font_fmt_txt_cmap_t&&) = &lv_font_fmt_txt_cmap_t::operator=;
lv_font_fmt_txt_kern_pair_t& (lv_font_fmt_txt_kern_pair_t::*_85)(lv_font_fmt_txt_kern_pair_t&&) = &lv_font_fmt_txt_kern_pair_t::operator=;
lv_font_fmt_txt_kern_classes_t& (lv_font_fmt_txt_kern_classes_t::*_86)(lv_font_fmt_txt_kern_classes_t&&) = &lv_font_fmt_txt_kern_classes_t::operator=;
lv_font_fmt_txt_dsc_t& (lv_font_fmt_txt_dsc_t::*_87)(lv_font_fmt_txt_dsc_t&&) = &lv_font_fmt_txt_dsc_t::operator=;
lv_animimg_t& (lv_animimg_t::*_88)(lv_animimg_t&&) = &lv_animimg_t::operator=;
lv_image_t& (lv_image_t::*_89)(lv_image_t&&) = &lv_image_t::operator=;
lv_arc_t& (lv_arc_t::*_90)(lv_arc_t&&) = &lv_arc_t::operator=;
_lv_bar_anim_t& (_lv_bar_anim_t::*_91)(_lv_bar_anim_t&&) = &_lv_bar_anim_t::operator=;
lv_bar_t& (lv_bar_t::*_92)(lv_bar_t&&) = &lv_bar_t::operator=;
lv_button_t& (lv_button_t::*_93)(lv_button_t&&) = &lv_button_t::operator=;
lv_buttonmatrix_t& (lv_buttonmatrix_t::*_94)(lv_buttonmatrix_t&&) = &lv_buttonmatrix_t::operator=;
lv_calendar_date_t& (lv_calendar_date_t::*_95)(lv_calendar_date_t&&) = &lv_calendar_date_t::operator=;
lv_calendar_t& (lv_calendar_t::*_96)(lv_calendar_t&&) = &lv_calendar_t::operator=;
lv_chart_series_t& (lv_chart_series_t::*_97)(lv_chart_series_t&&) = &lv_chart_series_t::operator=;
lv_chart_cursor_t& (lv_chart_cursor_t::*_98)(lv_chart_cursor_t&&) = &lv_chart_cursor_t::operator=;
lv_chart_t& (lv_chart_t::*_99)(lv_chart_t&&) = &lv_chart_t::operator=;
lv_dropdown_list_t& (lv_dropdown_list_t::*_100)(lv_dropdown_list_t&&) = &lv_dropdown_list_t::operator=;
lv_imagebutton_src_info_t& (lv_imagebutton_src_info_t::*_101)(lv_imagebutton_src_info_t&&) = &lv_imagebutton_src_info_t::operator=;
lv_imagebutton_t& (lv_imagebutton_t::*_102)(lv_imagebutton_t&&) = &lv_imagebutton_t::operator=;
lv_keyboard_t& (lv_keyboard_t::*_103)(lv_keyboard_t&&) = &lv_keyboard_t::operator=;
lv_led_t& (lv_led_t::*_104)(lv_led_t&&) = &lv_led_t::operator=;
lv_line_t& (lv_line_t::*_105)(lv_line_t&&) = &lv_line_t::operator=;
lv_menu_load_page_event_data_t& (lv_menu_load_page_event_data_t::*_106)(lv_menu_load_page_event_data_t&&) = &lv_menu_load_page_event_data_t::operator=;
lv_menu_history_t& (lv_menu_history_t::*_107)(lv_menu_history_t&&) = &lv_menu_history_t::operator=;
lv_menu_t& (lv_menu_t::*_108)(lv_menu_t&&) = &lv_menu_t::operator=;
lv_msgbox_t& (lv_msgbox_t::*_109)(lv_msgbox_t&&) = &lv_msgbox_t::operator=;
lv_roller_t& (lv_roller_t::*_110)(lv_roller_t&&) = &lv_roller_t::operator=;
lv_scale_section_t& (lv_scale_section_t::*_111)(lv_scale_section_t&&) = &lv_scale_section_t::operator=;
lv_scale_t& (lv_scale_t::*_112)(lv_scale_t&&) = &lv_scale_t::operator=;
lv_slider_t& (lv_slider_t::*_113)(lv_slider_t&&) = &lv_slider_t::operator=;
lv_spangroup_t& (lv_spangroup_t::*_114)(lv_spangroup_t&&) = &lv_spangroup_t::operator=;
lv_spinbox_t& (lv_spinbox_t::*_115)(lv_spinbox_t&&) = &lv_spinbox_t::operator=;
lv_textarea_t& (lv_textarea_t::*_116)(lv_textarea_t&&) = &lv_textarea_t::operator=;
lv_switch_t& (lv_switch_t::*_117)(lv_switch_t&&) = &lv_switch_t::operator=;
lv_table_cell_t& (lv_table_cell_t::*_118)(lv_table_cell_t&&) = &lv_table_cell_t::operator=;
lv_table_t& (lv_table_t::*_119)(lv_table_t&&) = &lv_table_t::operator=;
lv_tabview_t& (lv_tabview_t::*_120)(lv_tabview_t&&) = &lv_tabview_t::operator=;
lv_tileview_t& (lv_tileview_t::*_121)(lv_tileview_t&&) = &lv_tileview_t::operator=;
lv_tileview_tile_t& (lv_tileview_tile_t::*_122)(lv_tileview_tile_t&&) = &lv_tileview_tile_t::operator=;
lv_win_t& (lv_win_t::*_123)(lv_win_t&&) = &lv_win_t::operator=;
lv_sysmon_backend_data_t& (lv_sysmon_backend_data_t::*_124)(lv_sysmon_backend_data_t&&) = &lv_sysmon_backend_data_t::operator=;
lv_subject_value_t& (lv_subject_value_t::*_125)(lv_subject_value_t&&) = &lv_subject_value_t::operator=;
lv_subject_t& (lv_subject_t::*_126)(lv_subject_t&&) = &lv_subject_t::operator=;
struct _lv_observer_t& (_lv_observer_t::*_127)(struct _lv_observer_t&&) = &_lv_observer_t::operator=;
struct _lv_theme_t& (_lv_theme_t::*_128)(struct _lv_theme_t&&) = &_lv_theme_t::operator=;
struct _lv_global_t& (_lv_global_t::*_129)(struct _lv_global_t&&) = &_lv_global_t::operator=;
lv_draw_sw_unit_t& (lv_draw_sw_unit_t::*_130)(lv_draw_sw_unit_t&&) = &lv_draw_sw_unit_t::operator=;
lv_draw_sw_blend_dsc_t& (lv_draw_sw_blend_dsc_t::*_131)(lv_draw_sw_blend_dsc_t&&) = &lv_draw_sw_blend_dsc_t::operator=;
_lv_draw_sw_blend_fill_dsc_t& (_lv_draw_sw_blend_fill_dsc_t::*_132)(_lv_draw_sw_blend_fill_dsc_t&&) = &_lv_draw_sw_blend_fill_dsc_t::operator=;
_lv_draw_sw_blend_image_dsc_t& (_lv_draw_sw_blend_image_dsc_t::*_133)(_lv_draw_sw_blend_image_dsc_t&&) = &_lv_draw_sw_blend_image_dsc_t::operator=;
_lv_draw_sw_mask_common_dsc_t& (_lv_draw_sw_mask_common_dsc_t::*_134)(_lv_draw_sw_mask_common_dsc_t&&) = &_lv_draw_sw_mask_common_dsc_t::operator=;
lv_draw_sw_mask_line_param_t& (lv_draw_sw_mask_line_param_t::*_135)(lv_draw_sw_mask_line_param_t&&) = &lv_draw_sw_mask_line_param_t::operator=;
lv_draw_sw_mask_angle_param_t& (lv_draw_sw_mask_angle_param_t::*_136)(lv_draw_sw_mask_angle_param_t&&) = &lv_draw_sw_mask_angle_param_t::operator=;
_lv_draw_sw_mask_radius_circle_dsc_t& (_lv_draw_sw_mask_radius_circle_dsc_t::*_137)(_lv_draw_sw_mask_radius_circle_dsc_t&&) = &_lv_draw_sw_mask_radius_circle_dsc_t::operator=;
lv_draw_sw_mask_radius_param_t& (lv_draw_sw_mask_radius_param_t::*_138)(lv_draw_sw_mask_radius_param_t&&) = &lv_draw_sw_mask_radius_param_t::operator=;
lv_draw_sw_mask_fade_param_t& (lv_draw_sw_mask_fade_param_t::*_139)(lv_draw_sw_mask_fade_param_t&&) = &lv_draw_sw_mask_fade_param_t::operator=;
struct _lv_draw_sw_mask_map_param_t& (_lv_draw_sw_mask_map_param_t::*_140)(struct _lv_draw_sw_mask_map_param_t&&) = &_lv_draw_sw_mask_map_param_t::operator=;
