// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

[assembly:InternalsVisibleTo("lvgl")]

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

public unsafe partial class RTL_CRITICAL_SECTION
{
    [StructLayout(LayoutKind.Sequential, Size = 40, Pack = 8)]
    public partial struct __Internal
    {
        internal __IntPtr DebugInfo;
        internal int LockCount;
        internal int RecursionCount;
        internal __IntPtr OwningThread;
        internal __IntPtr LockSemaphore;
        internal ulong SpinCount;
    }
}

public unsafe partial class RTL_CONDITION_VARIABLE
{
    [StructLayout(LayoutKind.Sequential, Size = 8)]
    public partial struct __Internal
    {
        internal __IntPtr Ptr;
    }
}
